# Generated by Django 4.1.3 on 2022-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
    ]
